-- AlterTable
ALTER TABLE "Coin" ADD COLUMN     "marketCap" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "priceChangePercentage1h" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "priceChangePercentage24h" DOUBLE PRECISION NOT NULL DEFAULT 0;
